// src/config/fieldLabels.ts
// Labels legibles para campos sueltos que NO pertenecen a ningun grupo de fieldGroups.ts

export const FIELD_LABELS: Record<string, string> = {
  nombre_carpeta:     'Nombre de carpeta',
  id_familia:         'ID de familia',
  fecha_subida:       'Fecha de subida',

  p1_barrio_zona:        'Barrio / zona',
  p1_encuestadores:      'Encuestadores',
  p1_familia:            'Familia',
  p1_fecha:              'Fecha',
  p1_material_pared_anexo:       'Material de la pared donde se anexa',
  p1_material_pared_anexo_otro:  'Material de la pared (otro)',
  p1_motivo_independiente:       'Motivo: baño independiente',
  p1_motivo_independiente_otro:  'Motivo independiente (otro)',
  p1_acceso_agua:                'Tiene acceso al agua',
  p1_conexion_ms:                'El módulo sanitario se conecta a',
  p1_distancia_a_pozo:           'Distancia al pozo',
  p1_electricidad_aclarar_enchufe: 'Aclaración ubicación del enchufe',
  p1_agua_dejar_lista_materials:   'Lista de materiales a conseguir (agua)',
  p1_lider_construccion:           'Líder de construcción',
  p1_lider_construccion_justificar:'Justificación líder de construcción',
  p1_altura_pared_vivienda: 'Altura pared vivienda',
  p1_altura_pared_alta:     'Altura pared alta',
  p1_altura_pared_baja:     'Altura pared baja',
  p1_largo_pared:           'Largo de la pared',
  p1_altura_visible_cm:     'Altura visible (cm)',
  p1_cant_bebes:            'Cantidad de bebés',
  p1_cant_ninos_as:         'Cantidad de niños/as',
  p1_cant_adultas_mujeres:  'Cantidad de adultas mujeres',
  p1_cant_adultos_varones:  'Cantidad de adultos varones',
  p1_pozo_ciego_otro_texto: 'Pozo ciego — otro (detalle)',

  p2_tipo_anexado:                  'Tipo de anexado',
  p2_plano_terreno_descripcion:     'Descripción del plano del terreno',

  p3_fecha:               'Fecha',
  p3_barrio_zona:          'Barrio / zona',
  p3_encuestadores:        'Encuestadores',
  p3_integrantes_texto_crudo: 'Integrantes de la familia',
  p3_subsidio_cual:        '¿Cuál subsidio?',
  p3_gasto_significativo_descripcion: 'Descripción del gasto significativo',
  p3_gasto_significativo_monto:       'Monto del gasto significativo',
  p3_terreno_de_quien:           'De quién es el terreno',
  p3_terreno_espacio_construir:  'Espacio para construir',
  p3_terreno_anios_viviendo:     'Años viviendo en el terreno',
  p3_terreno_aspectos_referencias: 'Aspectos / referencias del terreno',
  p3_terreno_direccion:    'Dirección del terreno',
  p3_terreno_calle_frontal:     'Calle frontal',
  p3_terreno_calle_frontal_nro: 'Número (calle frontal)',
  p3_terreno_calle_trasera:     'Calle trasera',
  p3_terreno_calle_lateral_1:   'Calle lateral 1',
  p3_terreno_calle_lateral_2:   'Calle lateral 2',
  p3_bano_distancia:       'Distancia al baño',
  p3_pozo_profundidad:     'Profundidad del pozo',
  p3_pozo_hace_cuanto:     '¿Hace cuánto el pozo?',
  p3_pozo_esta_calzado:    '¿El pozo está calzado?',
  p3_pozo_tiene_tapa:      '¿El pozo tiene tapa?',
  p3_hay_lugar_biopozo:    '¿Hay lugar para biopozo?',
  p3_biopozo_mucha_sombra:           '¿Mucha sombra en la zona del biopozo?',
  p3_biopozo_tierra_negra_absorbente:'¿Tierra negra absorbente?',
  p3_fuente_agua:                    'Fuente de agua',
  p3_fuente_agua_profundidad_perforacion: 'Profundidad de perforación',
  p3_fuente_agua_tanque_en_altura:        '¿Tanque de agua en altura?',
  p3_acceso_agua_cat:      'Acceso al agua',
  p3_estado_general:       'Estado general',
  p3_proyecto_ampliar_3_meses: '¿Proyecto de ampliar en 3 meses?',
  p3_proyecto_ampliar_estado:  'Estado del proyecto de ampliación',
  p3_tienen_electricidad:  '¿Tienen electricidad?',
  p3_terreno_inundable:    '¿El terreno es inundable?',
  p3_terreno_inundable_altura_maxima: 'Altura máxima de inundación',
  p3_contacto_1_telefono:  'Teléfono contacto 1',
  p3_contacto_1_dueno:     'Contacto 1 es dueño/a',
  p3_contacto_2_telefono:  'Teléfono contacto 2',
  p3_contacto_2_dueno:     'Contacto 2 es dueño/a',
  p3_prioridad:            'Prioridad',
  p3_comentarios:          'Comentarios',
  p3_ingreso_por_trabajo:  'Ingreso por trabajo',
  p3_ingreso_por_subsidio: 'Ingreso por subsidio',
  p3_ingreso_total:        'Ingreso total',

  p4_fecha:           'Fecha',
  p4_barrio_zona:     'Barrio / zona',
  p4_encuestadores:   'Encuestadores',
  p4_familia:         'Familia',
  p4_tienen_bano:                    '¿Tienen baño?',
  p4_tienen_bano_no_donde_resuelven: 'Si no tienen baño, ¿dónde resuelven?',
  p4_agua_en_bano:                   '¿Tienen agua en el baño?',
  p4_agua_en_bano_no_donde_traen:    'Si no, ¿de dónde traen el agua?',
  p4_calientan_agua:                 '¿Cómo calientan el agua?',
  p4_calientan_agua_otro_texto:      'Cómo calientan el agua (otro)',
  p4_posibilidades_construccion:     'Posibilidades de construcción',
  p4_tienen_interes_programa:           '¿Tienen interés en el programa?',
  p4_tienen_interes_programa_comentario:'Comentario sobre interés en el programa',
  p4_tipo_anexado_2da_visita:  'Tipo de anexado (2da visita)',
  p4_vivienda_observaciones:   'Observaciones de la vivienda',
  p4_casa_inclinada_desaplomada: '¿Casa inclinada / desaplomada?',
  p4_prioridad_2da_visita:     'Prioridad (2da visita)',
  p4_croquis_final_descripcion:'Descripción del croquis final',
  p4_personas_en_vivienda:     'Personas en la vivienda',
  p4_personas_en_terreno:      'Personas en el terreno',
  p4_mujeres_etapa_menstrual_cantidad: 'Cantidad de mujeres en etapa menstrual',

  _observaciones: 'Observaciones',
  _dudas:         'Dudas',
};

export function getFieldLabel(key: string): string {
  return FIELD_LABELS[key] ?? key;
}